- name: Nginx permission
  ansible.builtin.file:
    path: /var/cache/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: "0700"
    recurse: true

- name: Change nginx config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx
    owner: root
    group: root
    mode: "0644"
  register: nginx_sync

- name: Check local configs
  delegate_to: localhost
  ansible.builtin.stat:
    path: files/{{ inventory_hostname }}/nginx
  register: nginx_config_files

- name: Delete default config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  register: nginx_sync
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  when: nginx_config_files.stat.exists

- name: Copy configs
  ansible.builtin.copy:
    src: files/{{ inventory_hostname }}/nginx
    dest: /etc/
    owner: www-data
    group: www-data
    mode: "0700"
    decrypt: true
  register: nginx_sync
  when: nginx_config_files.stat.exists

- name: Set correct permissions on files
  ansible.builtin.file:
    path: /etc/nginx/{{ item }}
    mode: "0640"
  with_fileglob:
    - "files/{{ inventory_hostname }}/nginx/*"
  when: nginx_config_files.stat.exists

- name: Check configs
  ansible.builtin.shell: nginx -t
  warn: false  # E301
  register: nginx_validate
  when: nginx_sync.changed

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_validate
