- name:        change nginx config
  copy:
    src:       nginx.conf
    dest:      /etc/nginx
    owner:     root
    group:     root
    mode:      0644
  register:    nginx_sync

- name:        check local configs
  delegate_to: localhost
  stat:
    path:      files/{{ inventory_hostname }}/nginx
  register:    nginx_config_files

- name:        delete default config
  file:
    path:      "{{ item }}"
    state:     absent
  register:    nginx_sync
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  when:        nginx_config_files.stat.exists

- name:        copy configs
  copy:
    src:       files/{{ inventory_hostname }}/nginx
    dest:      /etc/
    owner:     root
    group:     root
    decrypt:   true
  register:    nginx_sync
  when:        nginx_config_files.stat.exists

- name:        check configs
  shell:       nginx -t
  register:    nginx_validate
  when:        nginx_sync.changed

- name:        restart nginx
  service:
    name:      nginx
    state:     restarted
  when:        nginx_validate
